// <auto-generated />
using System;
using CRMALL.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CRMALL.Infra.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20201023194810_Atualizacao-Campos-Obrigatorios")]
    partial class AtualizacaoCamposObrigatorios
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CRMALL.Domain.Entities.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnName("data_nascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("nome")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Sexo")
                        .HasColumnName("sexo")
                        .HasColumnType("int");

                    b.Property<long?>("endereco_id")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("endereco_id");

                    b.ToTable("cliente");
                });

            modelBuilder.Entity("CRMALL.Domain.Entities.Endereco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("bigint");

                    b.Property<string>("Bairro")
                        .HasColumnName("bairro")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Cep")
                        .HasColumnName("cep")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Cidade")
                        .HasColumnName("cidade")
                        .HasColumnType("varchar(45)");

                    b.Property<string>("Complemento")
                        .HasColumnName("complemento")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Estado")
                        .HasColumnName("estado")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Logradouro")
                        .HasColumnName("logradouro")
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("Numero")
                        .HasColumnName("numero")
                        .HasColumnType("int");

                    b.Property<int?>("TipoEndereco")
                        .HasColumnName("tipo_endereco")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("endereco");
                });

            modelBuilder.Entity("CRMALL.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("CRMALL.Domain.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("endereco_id");
                });
#pragma warning restore 612, 618
        }
    }
}
